import cat1 from "../../images/cat-13.png";

export const SMALL_CARD_DATA = [
  { text: "Milk & Diaries", icon: cat1, items: "14" },
  { text: "Clothing", icon: cat1, items: "34" },
  { text: "Pet Foods & Toy", icon: cat1, items: "34" },
  { text: "Baking Material", icon: cat1, items: "34" },
  { text: "Fresh Fruit", icon: cat1, items: "34" },
  { text: "Milk & Diaries", icon: cat1, items: "34" },
  { text: "Clothing", icon: cat1, items: "34" },
  { text: "Wines & Drinks", icon: cat1, items: "34" },
  { text: "Fresh Seafood", icon: cat1, items: "34" },
  { text: "Fast Food", icon: cat1, items: "34" },
  { text: "Vegetables", icon: cat1, items: "34" },
  { text: "Bread & Juice", icon: cat1, items: "34" },
  { text: "Wines & Drinks", icon: cat1, items: "34" },
  { text: "Fresh Seafood", icon: cat1, items: "34" },
  { text: "Milk & Diaries", icon: cat1, items: "14" },
  { text: "Clothing", icon: cat1, items: "34" },
  { text: "Pet Foods & Toy", icon: cat1, items: "34" },
  { text: "Baking Material", icon: cat1, items: "34" },
  { text: "Fresh Fruit", icon: cat1, items: "34" },
  { text: "Milk & Diaries", icon: cat1, items: "34" },
  { text: "Clothing", icon: cat1, items: "34" },
  { text: "Wines & Drinks", icon: cat1, items: "34" },
  { text: "Fresh Seafood", icon: cat1, items: "34" },
  { text: "Fast Food", icon: cat1, items: "34" },
  { text: "Vegetables", icon: cat1, items: "34" },
  { text: "Bread & Juice", icon: cat1, items: "34" },
  { text: "Wines & Drinks", icon: cat1, items: "34" },
  { text: "Fresh Seafood", icon: cat1, items: "34" },
];
